### PR TITLE
VS Code Support

### PR DESCRIPTION
**Pull request by TheFlowerVixen**
something to make things a little easier
a little unprofessional but change as you wish

### CODE REVIEW

**Comment by NathanX-S** [comment]
I really don't think these should be on the repo, if someone feels they want these I'm sure they'd be capable of adding it themselves.

**Comment by TheFlowerVixen** [comment]
@jwcotejr said himself it'd be useful for him, since he uses vs code sometimes himself. it'd also make people's lives a lot easier in case they prefer vs code. if anyone disagrees they can close this PR, it's up to them.

**Comment by NathanX-S** [comment]
If it works, it works.

**Comment by NathanX-S** [comment]
This PR could be expanded to other programs, do you think you'd be able to support PyCharm as well?

**Pull request merged**
