### PR TITLE
OTP connectivity support.

### PR DESCRIPTION
**Pull request by LittleToonCat**
The PR contains the following:
- The `astronSupport` boolean is now a `__builtin__` definition.
- Added OTP client message types.
- Added an older copy of `DoInterestManager` into the source which uses OTP based interest messages.
- Override some functions in `OTPInternalRepository` if `astronSuport` is False to support OTP message types.
- Added some other messages in `AiMsgTypes.py` (These are being used in my OTP server code, but this might differ depending on the code other people might use)
- Probably some other stuff I forgotten because I need to learn how to do separate commits every once in awhile. :/

OTP conectivity requires open-toontown/panda3d#5 to be merged for it to work.

### CODE REVIEW

**Comment by jwcotejr** [comment]
Thank you for this!

First and foremost, I feel as though it's worth raising the question as to whether or not some of these changes might belong in our Panda3D fork rather than the Open Toontown repository itself. That is, having an OTP-compatible `DoInterestManager` in here, and adding the OTP message types into here rather than reintroducing them to Panda3D itself. It's worth noting that I am not implying here that these changes should be made, or that they are even necessary; truth be told, I don't know what the best course of action is, which is why I am bringing this up in the first place.

Furthermore, I noticed that you added message types into the Open Toontown code that is used by your OTP server implementation. While this works well for those of us who have access to your OTP server, this is not likely to apply across the board for all potential OTP servers. That by itself raises the question as to how this should be approached, and whether or not your OTP server's message types should indirectly become the "standard" as a result.

**Comment by LittleToonCat** [comment]
That's true, Couple of the stuff on this PR should be in the Panda3D repo instead (like the client message types and the OTP-compatible `DoInterestManager`), but I wasn't really thinking when i opened this PR.  I'll get to it when I have the time.

Also, I agree with what you said about my internal message types might not be compatible to other potential OTP solutions.  I'm open to discussions of how we can approach to possibly satisfy the needs and compatibility with all OTP server projects.

**Comment by jwcotejr** [comment]
> That's true, Couple of the stuff on this PR should be in the Panda3D repo instead (like the client message types and the OTP-compatible DoInterestManager), but I wasn't really thinking when i opened this PR. I'll get to it when I have the time.

No worries! I wasn't sure as to whether or not that was an explicit decision that was made on your part, so I just wanted to clarify.

> Also, I agree with what you said about my internal message types might not be compatible to other potential OTP solutions. I'm open to discussions of how we can approach to possibly satisfy the needs and compatibility with all OTP server projects.

I'm thinking that there is no "perfect" way of approaching this; to my knowledge, we don't know what Disney's internal message types were for their OTP server, so we're left to figure that out on our own.

What I'm thinking is that we'll ultimately want to decide on what internal message types we should be using for OTP servers, and document those message types so that potential OTP server projects can implement these message types into their project, should they choose to support Open Toontown with their OTP server.

Thanks again!

**Comment by LittleToonCat** [comment]
Closing this as I am planning to re do most of this again and submit part of this PR into separate PRs.

**Pull request closed without merging**
