### PR TITLE
The Definitive PNG+TTF Migration

### PR DESCRIPTION
**Pull request by loonaticx**
Resources PR (might be laggy to load) https://github.com/open-toontown/resources/pull/3

I had these branches hanging around my custom fork for nearly a year, forgetting about it. It might be a bit of an overwhelming refactor, but with consideration that open-toontown is trying to modernize Toontown's resources, might as well take the big leap here.

It was a bit difficult for me to _not_ to include TTF fonts with the PNG conversion since some of the modulate/luminance-based fonts misbehave a bit.

While I've tested this to some extent, this may introduce unintended graphical bugs. Before this+resources PR is merged I recommend checking them out on your own machine.  Feel free to comment any graphical bugs you see and I'll address them as soon as I can.

### CODE REVIEW

**Comment by NathanX-S** [comment]
This PR does reveal a concerning amount of "hard coded" texture paths, resulting in a commit like this even needing to exist in the first place. Will probably check this out on my machine shortly. 🤷‍♂️

**Comment by loonaticx** [comment]
> This PR does reveal a concerning amount of "hard coded" texture paths, resulting in a commit like this even needing to exist in the first place. Will probably check this out on my machine shortly. 🤷‍♂️

Welcome to Toontown!

Actually, not all hardcoded texture paths are a bad thing. They can be far more optimal than rather, say, using a texture card Bamfile instead.

This PR is also primarily focused on the migration to PNG and nothing concerned about the way textures are called in-game wrt the codebase.

**Comment by LittleToonCat** [comment]
Everything seems to work well on my machine without any notable problems.  On both Linux (Ubuntu 20.04) and Windows 10 running latest Panda.

> This PR does reveal a concerning amount of "hard coded" texture paths, resulting in a commit like this even needing to exist in the first place. Will probably check this out on my machine shortly. man_shrugging

You have any status on your testing, @NathanX-S?

**Comment by LittleToonCat** [comment]
Final call: If nobody has any objections or have any issues to this soon, I'm going to merge the pull requests.

**Comment by loonaticx** [comment]
> Final call: If nobody has any objections or have any issues to this soon, I'm going to merge the pull requests.

Bump?

**Pull request merged**
