### PR TITLE
General: Add files for Silicon support (aka Mac M1)

### PR DESCRIPTION
**Pull request by LuigiFan25**

### CODE REVIEW

**Comment by DarthMDev** [comment]
Any reason why this hasnt been merged in?

**Comment by opentoontown** [comment]
two reasons:

1.) we prefer to host our own download links for binaries such as panda3d
2.) we are in the process of dropping astron support, so it would be a bit counterproductive to merge in a binary that would soon be eliminated anyway

thank you

**Comment by EmeraldShift** [comment]
What will be replacing Astron?

**Comment by Kobun42** [comment]
> What will be replacing Astron?

Not 100% sure but considering this project is attempting to keep things as original as possible (barring the jump to Python 3.x and the newer version of P3D being used), most likely an emulator/re-implementation of the actual Disney OTP server rather than the Astron implementation TTR (and plenty of other servers) used. Though I could end up being wrong and they could end up using something completely different.

**Pull request closed without merging**
