### PR TITLE
toon: player can see own chat now, awesome

### PR DESCRIPTION
**Pull request by NathanX-S**

### CODE REVIEW

**Comment by LittleToonCat** [comment]
While this does fix the bug where a player can see their own chat, but I'm closing this because that's not how the whole chat infrastructure works.  It has to go through various security and safety checks before it can be sent off to other players, such as checking the whitelist (SpeedChat+ dictionary), making sure that words not in the whitelist can be seen with the player's True Friends, and most importantly, make sure that none of the dirty language goes through at all.  Your PR has no security, and we don't want to ship off chat without security, that would be bad.

@jwcotejr will be most likely go through the whole thing himself later on.  Best leaving it to him.

**Comment by NathanX-S** [comment]
I'm very confused here. The checks you talk about do occur in setTalk from what I can tell. You mention a fully secure infrastructure, but as far as I can tell it's all done on the client, if not am majority.

**Comment by NathanX-S** [comment]
TTOff uses a client-server model for checks and balances, but that does not seem the case in TTO.

**Comment by NathanX-S** [comment]
Apologies for the above, @jwcotejr explained how the system *should* work to me. And why the current implementation doesn't work. The OTP would intercept setTalk and modify it accordingly before dispatching the corrected setTalk to the clients. This makes a lot more sense. Cheers.

**Pull request closed without merging**
