### PR TITLE
Fix golf not working

### PR DESCRIPTION
**Pull request by SamuelT24**
Also commented out the 'logout' button on the pick-a-toon screen (I didn't make supportsrelogin return 0 because that would've removed the ability to reconnect after disconnecting) and changed a config setting so that the game window will now open in the top left rather than in the middle.

### CODE REVIEW

**Review by DarthMDev — APPROVED** [review]

**Comment by NathanX-S** [comment]
Suggest that you separate your commits somehow.

**Comment by DarthMDev** [comment]
Some of these commits probably belong in their own pr

**Comment by SamuelT24** [comment]
If it helps, I can close this one and open a new one with just the golf changes if you're not happy with the other changes.

**Comment by LittleToonCat** [comment]
> If it helps, I can close this one and open a new one with just the golf changes if you're not happy with the other changes.

Yes, please separate these commits into different pull requests to make things easier, closing this one.

**Pull request closed without merging**
